export const initialState = {
  posts: {
    data: [
      // {
      //   id: '1as',
      //   title: 'Lorem ipsum 1',
      //   content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
      //   datePublication: '2021.03.12',
      //   dateLastUpdate: '2021.03.27',
      //   email: 'john@lorem.com',
      //   status: 'published',
      //   image: 'https://placeimg.com/640/480/tech/1',
      //   price: '100',
      //   phone: '123456789',
      //   location: 'Warsaw',
      // },
      // {
      //   id: '2sd',
      //   title: 'Lorem ipsum 2',
      //   content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
      //   datePublication: '2021.02.23',
      //   dateLastUpdate: '2021.04.11',
      //   email: 'donald@lorem.com',
      //   status: 'closed',
      //   image: 'https://placeimg.com/640/480/tech/2',
      //   price: '150',
      //   phone: '987654321',
      //   location: 'London',
      // },
      // {
      //   id: '3jh',
      //   title: 'Lorem ipsum 3',
      //   content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
      //   datePublication: '2021.01.29',
      //   dateLastUpdate: '2021.01.29',
      //   email: 'jeremy@lorem.com',
      //   status: 'draft',
      //   image: 'https://placeimg.com/640/480/tech/3',
      //   price: '120',
      //   phone: '111222333',
      //   location: 'Berlin',
      // },
      // {
      //   id: '4fj',
      //   title: 'Lorem ipsum 4',
      //   content: 'Nulla ac turpis rutrum pede sit amet sapien eu odio. Morbi a blandit quam eros ac turpis egestas. Suspendisse ac quam in dictum eget, elementum nunc. Nulla venenatis arcu',
      //   datePublication: '2021.01.23',
      //   dateLastUpdate: '2021.04.15',
      //   email: 'manuela@lorem.com',
      //   status: 'published',
      //   image: 'https://placeimg.com/640/480/tech/4',
      //   price: '88',
      //   phone: '432543654',
      //   location: 'Paris',
      // },
    ],
    loading: {
      active: false,
      error: false,
      addOnePost: false,
      editOnePost: false,
    },
    onePost: {

    },
  },
  user: {
    active: true,
  },
};
